### ISSUE TITLE
Oops! The padding left & right is not identical to top & bottom - Hacktoberfest 2020

### ISSUE THREAD

**Issue by ashiishme** [ashiishme/react-share-ui#1]
After going through the UI, the padding in the list item doesn't looks identical. The left & right spacing is larger than the top & bottom. 

If anyone interested to make this small CSS fix:
- Please fork this repository
- Make necessary changes
- Send a PR

This issue is open for Hacktoberfest 2020 & before you start to fix, comment below so that others can know about it.

![image](https://user-images.githubusercontent.com/18111862/94754849-22edbd80-03b2-11eb-8764-72a6bb8c9f62.png)

**Comment by ShubhamVerma1811** [comment]
Hey
Can I give it a try?

**Comment by ashiishme** [comment]
Ofcourse @ShubhamVerma1811, please go ahead.

**Comment by sharkaie** [comment]
i also want to try

**Comment by ashiishme** [comment]
Hi @vedantby, it is not possible for multiple users to make fix this issue but you can create new issues if found any or make a feature request. I will label it.

**Comment by sharkaie** [comment]
Their should be a header as its, looking incomplete without it.

**Comment by ShubhamVerma1811** [comment]
Hey @ashiishme 
So I understand correctly, the left/right padding change when I resize.
The top/bottom padding is constant, So how much top/bottom padding do you want?

**Comment by ashiishme** [comment]
> Their should be a header as its, looking incomplete without it.

Nice, please make a feature request & you can start working on it.

**Comment by ashiishme** [comment]
> Hey @ashiishme
> So I understand correctly, the left/right padding change when I resize.
> The top/bottom padding is constant, So how much top/bottom padding do you want?

@ShubhamVerma1811 It should look identical. All the 4 sides must be even. If you can manage to fix the left & right padding rather than increasing top & bottom, that would be much better.

**Comment by ShubhamVerma1811** [comment]
Hey @ashiishme 
I have submitted a pull req here #2

**Comment by ashiishme** [comment]
Thank you @ShubhamVerma1811

**Comment by ShubhamVerma1811** [comment]
> Thank you @ShubhamVerma1811 

I am so happy.
This was my first pull request.

**Comment by ashiishme** [comment]
Congrats :champagne:
