### ISSUE TITLE
Fix: Padding of the list container doesn't look good - Hacktoberfest 2020

### ISSUE THREAD

**Issue by ashiishme** [ashiishme/react-share-ui#3]
Recently after the fixes applied on #1. The padding on each side of the list container is too big ( need to reduce the padding ). The UI doesn't look good with such large amount of padding.

This issue is only for beginners who are interested to contribute on open-source.

For reference:

![too-big-padding](https://user-images.githubusercontent.com/18111862/94984066-de0b8780-0567-11eb-8288-997f7069f19e.png)

If you are interested to fix it, just comment below & I will assign.

**Comment by yogeswarl** [comment]
Can I take this up

**Comment by AN-2000** [comment]
Can I do this?

**Comment by sakshi-dhamija** [comment]
Hello, Can I take up this issue?

**Comment by ashiishme** [comment]
This issue has been fixed with #4.
